const UNITY_PATHS = [
  "/euvc2023/EhimeWebGL/Build/66037178c278503228e0f5f2511b301a.data",
  "/euvc2023/EhimeWebGL/Build/dd9ff5803245e1a33787af0195f3d3d8.wasm",
  "/euvc2023/EhimeWebGL/Build/faf84e8f082175e7c8af023ce113f1ba.js",
];

const JPEG_PATHS = [
  "/euvc2023contents/board/jpg/01HOUBU.jpg",
  "/euvc2023contents/board/jpg/i_report.jpg",
  "/euvc2023contents/board/jpg/infinity.jpg",
  "/euvc2023contents/board/jpg/02KYOUIKU.jpg",
  "/euvc2023contents/board/jpg/03SHAKYO.jpg",
  "/euvc2023contents/board/jpg/04RIGAKU.jpg",
  "/euvc2023contents/board/jpg/05IGAKU.jpg",
  "/euvc2023contents/board/jpg/06KOUGAKU.jpg",
  "/euvc2023contents/board/jpg/07NOUGAKU.jpg",
  "/euvc2023contents/board/jpg/08JYUKEN.jpg",
  "/euvc2023contents/board/jpg/09OGYA.jpg",
  "/euvc2023contents/board/jpg/10HOSPITAL.jpg",
  "/euvc2023contents/board/jpg/11datascience.jpg",
  "/euvc2023contents/board/jpg/12rstock.jpg",
  "/euvc2023contents/board/jpg/13newcomer.jpg",
  "/euvc2023contents/board/jpg/14lr.jpg",
  "/euvc2023contents/board/jpg/15bousai.jpg",
  "/euvc2023contents/board/jpg/16SDGS.jpg",
  "/euvc2023contents/board/jpg/17byouin.jpg",
  "/euvc2023contents/board/jpg/18kikin.jpg",
  "/euvc2023contents/board/jpg/19mirainoaidaisei.jpg",
  "/euvc2023contents/board/jpg/20seikatujyouhou.jpg",
  "/euvc2023contents/board/jpg/21iikurashi.jpg",
  "/euvc2023contents/board/jpg/22youchien.jpg",
  "/euvc2023contents/board/jpg/23shougakko.jpg",
  "/euvc2023contents/board/jpg/24chuugaku.jpg",
  "/euvc2023contents/board/jpg/25koukou.jpg",
  "/euvc2023contents/board/jpg/26tokubetushien.jpg",
  "/euvc2023contents/board/jpg/27enshuurin.jpg",
  "/euvc2023contents/board/jpg/28museum.jpg",
];

const MP4_PATHS = [];

const LANDING_PATHS = [
  "/",
  "/favicon.ico",
  "/landing.html",
  "/landing/nicepage.css",
  "/landing/nicepage.js",
  "/landing/jquery-1.9.1.min.js",
  "/landing/B13_2.jpg",
  "/landing/eurc-2023.jpg",
  "/landing/euvc-landing-20230914.jpg",
];

const URL_MAPPINGS = [
  [/\/image\/news\/infinity.png$/, "/jpg/infinity.jpg"],
  [/\/image\/news\/i_report.png$/, "/jpg/i_report.jpg"],
  [/\/image\/news\/28museum.png$/, "/jpg/28museum.jpg"],
  [/\/image\/news\/27enshuurin.png$/, "/jpg/27enshuurin.jpg"],
  [/\/image\/news\/26tokubetsushien.png$/, "/jpg/26tokubetsushien.jpg"],
  [/\/image\/news\/25koukou.png$/, "/jpg/25koukou.jpg"],
  [/\/image\/news\/24chuugaku.png$/, "/jpg/24chuugaku.jpg"],
  [/\/image\/news\/23shougakko.png$/, "/jpg/23shougakko.jpg"],
  [/\/image\/news\/21iikurashi.png$/, "/jpg/21iikurashi.jpg"],
  [/\/image\/news\/19mirainoaidaisei.png$/, "/jpg/19mirainoaidaisei.jpg"],
  [/\/image\/news\/18kikin.png$/, "/jpg/18kikin.jpg"],
  [/\/image\/news\/17byouin.png$/, "/jpg/17byouin.jpg"],
  [/\/image\/news\/16SDGS.png$/, "/jpg/16SDGS.jpg"],
  [/\/image\/news\/15bousai.png$/, "/jpg/15bousai.jpg"],
  [/\/image\/news\/14lr.png$/, "/jpg/14lr.jpg"],
  [/\/image\/news\/13newcomer.png$/, "/jpg/13newcomer.jpg"],
  [/\/image\/news\/12rstock.png$/, "/jpg/12rstock.jpg"],
  [/\/image\/news\/11datascience.png$/, "/jpg/11datascience.jpg"],
  [/\/image\/news\/10HOSPITAL.png$/, "/jpg/10HOSPITAL.jpg"],
  [/\/image\/news\/09OGYA.png$/, "/jpg/09OGYA.jpg"],
  [/\/image\/news\/08JYUKEN.png$/, "/jpg/08JYUKEN.jpg"],
  [/\/image\/news\/07NOUGAKU.png$/, "/jpg/07NOUGAKU.jpg"],
  [/\/image\/news\/06KOUGAKU.png$/, "/jpg/06KOUGAKU.jpg"],
  [/\/image\/news\/05IGAKU.png$/, "/jpg/05IGAKU.jpg"],
  [/\/image\/news\/04RIGAKU.png$/, "/jpg/04RIGAKU.jpg"],
  [/\/image\/news\/03SHAKYO.png$/, "/jpg/03SHAKYO.jpg"],
  [/\/image\/news\/02KYOUIKU.png$/, "/jpg/02KYOUIKU.jpg"],
  [/\/image\/news\/01HOUBU.png$/, "/jpg/01HOUBU.jpg"],
  [/\/image\/news\/02KYOUIKU.png$/, "/jpg/02KYOUIKU.jpg"],
  [/\/image\/news\/25koukou.png$/, "/jpg/25koukou.jpg"],
  [/\/image\/news\/i_report.png$/, "/jpg/i_report.jpg"],
  [/\/image\/news\/20seikatujyouhou.png$/, "/jpg/20seikatujyouhou.jpg"],
  [/\/image\/news\/22youchien.png$/, "/jpg/22youchien.jpg"],
];
